### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by mithro** [tuliopereirab/arithmetic-encoder-av1#2]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by tuliopereirab** [comment]
Hi @mithro,

I just created the license file and included the **CERN Open Hardware Licence Version 2** in it.

I wasn't sure about which license I should use, so I looked for a permissive hardware design license and found this one on https://choosealicense.com/.

If you find a problem with it, please let me know and I'm going to fix it asap. 

Best regards,
Tulio

**Comment by mithro** [comment]
You are of course welcome to choose whatever license you think best. Google's recommended license is Apache 2.0 -- https://opensource.google/documentation/reference/thirdparty/licenses#hardware

**Comment by tuliopereirab** [comment]
Hi @mithro,

Just updated the license to Apache 2.0.
